### ISSUE TITLE
Feature request: Bookshelf page

### ISSUE THREAD

**Issue by darshil** [dragonman225/notablog#1]
Would be awesome to have the ability to view bookshelf on the website!

Example:
<img width="1675" alt="Screen Shot 2019-07-27 at 11 52 46 PM" src="https://user-images.githubusercontent.com/12867510/62001997-a97d7f80-b0c9-11e9-9161-0d4814a47cc8.png">

**Comment by dragonman225** [comment]
Interesting !
My idea : Maybe we can treat the bookshelf page as a post, **but** don't let it appear in the index list. Instead, link it elsewhere in the home page (just like how the current `about` page works !).

However, what prevent us from making the bookshelf work is actually the HTML renderer [nast-util-to-html](https://github.com/dragonman225/nast-util-to-html), which cannot render any database (table, list, gallery, ...) for now 😂.

So, some external work need to be done first before supporting this feature !

**Comment by darshil** [comment]
Yep, I think there are two ways that this can be done!

1) As you mentioned, have a separate page, similar to the `about` page.
2) Have another table for the bookshelf. Each item in the table would represent a book. 
 
Also, this type of concept could be very flexible and could be applied to a projects page or even a photo gallery page. Lots of potential here!
