### ISSUE TITLE
error with command "notablog generate ."

### ISSUE THREAD

**Issue by andrewalbo** [dragonman225/notablog#10]
when I run command "notablog generate ." on terminal, I receive a error message, screenshot below.

![Screenshot (308)](https://user-images.githubusercontent.com/66646869/86056335-97385e00-ba5d-11ea-8bd6-33fa786d1345.png)

**Comment by dragonman225** [comment]
Did you run that command inside a [notablog-starter](https://github.com/dragonman225/notablog-starter)?

**Comment by andrewalbo** [comment]
yes, but it didn't work. I removed the files and redo the procedure again, now it works.
