### ISSUE TITLE
Toggle lists on mobile devices

### ISSUE THREAD

**Issue by mk1564** [dragonman225/notablog#14]
Toggle lists do not look normal on mobile devices for example like below in the figure. 

![image](https://user-images.githubusercontent.com/43716217/101026669-2da90800-3545-11eb-9590-b397331d4837.jpeg)

**Comment by dragonman225** [comment]
It seems that you were using Safari.
Safari has a known bug that it doesn't respect `flex-wrap: nowrap`, the default wrapping method of flexbox, for some reasons, and I wasn't able to fix it.

Here is a new attempt: https://dragonman225.js.org/now-bugfix.html , but I don't have any devices running Safari, could you test it for me and report the result?

**Comment by mk1564** [comment]
Thanks for your reply. I still see the same bug in Safari, Chrome, and Microsoft Edge browsers in iOS mobile devices. Since I don't have Mac machine, I am not sure if this is only about iOS mobile devices or not.

**Comment by rounakdatta** [comment]
On macOS (desktop), I've verified that the toggle lists are expanding as expected on Safari, Chrome. I'll try debugging over an emulated iOS to see if the error can be reproduced.

**Comment by mk1564** [comment]
I found this morning that this issue is fixed on my iOS mobile device (Safari and Chrome).

**Comment by dragonman225** [comment]
Great! Then I'll close this.
