### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by RadioHeadach** [dragonman225/notablog#16]
In my perspective, the font is little bit larger than I used to see in many blogs or notion itself, how can I change the font size? Many thanks!!

**Comment by dragonman225** [comment]
You could change the font size in the theme, namely these files,
https://github.com/dragonman225/notablog-starter/blob/56333d79c0d9528bc0bf94ad616e5166c15acc66/themes/pure/layout/index.html#L31 (the template for the homepage)
https://github.com/dragonman225/notablog-starter/blob/56333d79c0d9528bc0bf94ad616e5166c15acc66/themes/pure/layout/post.html#L31 (the template for posts)
https://github.com/dragonman225/notablog-starter/blob/56333d79c0d9528bc0bf94ad616e5166c15acc66/themes/pure/layout/tag.html#L30 (the template for tags)

**Comment by RadioHeadach** [comment]
Thanks!
