### ISSUE TITLE
“notablog generate  .” clunky after "fetch site metadata"

### ISSUE THREAD

**Issue by frozenfish123** [dragonman225/notablog#18]
Thanks for your commitment, this repo helps me a lot !

Hwoever , when I update my blog, and "notablog generate", I found this step lagging for a long time.

before
![image](https://user-images.githubusercontent.com/53289454/124391533-9c408500-dd23-11eb-83df-34a252587b4a.png)

after
![image](https://user-images.githubusercontent.com/53289454/124391542-aa8ea100-dd23-11eb-8fde-7d6eea3a1ec8.png)

I'm looking forward to your reply, thank you!

**Comment by dragonman225** [comment]
If notablog can generate your site, then it's not an issue of notablog.
The long waiting time is probably due to unstable internet connection at your location or Notion's server being too busy to respond quickly.
