### ISSUE TITLE
The code format in Notion cannot be displayed after generation

### ISSUE THREAD

**Issue by gendlee** [dragonman225/notablog#25]
The code format in Notion cannot be displayed after generation. Is there any parameter to control OR is it just a bug?

Look forward to your reply or repair.

**Comment by dragonman225** [comment]
Could you share a screenshot of the issue and describe more about what you expect too see?

**Comment by gendlee** [comment]
<img width="590" alt="by your tool" src="https://user-images.githubusercontent.com/14952400/142729869-73c43ee4-2056-4554-9e32-6e00130df29f.png">

this is generated by your tool

<img width="321" alt="this is what I expect" src="https://user-images.githubusercontent.com/14952400/142729859-868981ec-1a6d-4014-b2dd-cbd686b19e29.png">

and this is what people prefer

**Comment by dragonman225** [comment]
What is the programming language of the code?

**Comment by gendlee** [comment]
Java

**Comment by dragonman225** [comment]
I've added it to the language list and it's working ([example](https://dragonman225.js.org/block-test.html#https://www.notion.so/4d3fe372fa5e4c4798394649ac3fea6f)). Please upgrade notablog to the latest version (v0.6.3) to enjoy it. Thanks for reporting this issue!

### Context

We're using [Prism](https://prismjs.com/) for code syntax highlighting, so as long as the programming language is supported by Prism, notablog should be able to support it. Potential issues may come from incorrect or incomplete [mapping](https://github.com/dragonman225/nast/blob/f8188c7ec5aad9fe9fe80f9b354d6e44c6f3fdd1/packages/nast-util-to-react/src/util-prismjs.ts#L164) of programming language names from Notion to Prism.
