### ISSUE TITLE
Images uploaded to Notion doesn't show up

### ISSUE THREAD

**Issue by dragonman225** [dragonman225/notablog#3]
If an image uploaded to Notion is used as icon or cover, it will not show up in the generated blog. The image is prefixed with https://s3-us-west-2.amazonaws.com/secure.notion-static.com/, and server responds 403.

**Comment by mayneyao** [comment]
```js
const parseImageUrl = (url, width) => {
    let rUrl
    if (url.startsWith("https://s3")) {
        let [parsedOriginUrl] = url.split("?")
        rUrl = `${NOTION_BASE_URL}/image/${encodeURIComponent(parsedOriginUrl).replace("s3.us-west", "s3-us-west")}`
    } else if (url.startsWith("/image")) {
        rUrl = `${NOTION_BASE_URL}${url}`
    } else {
        rUrl = url
    }

    if (width) {
        return `${rUrl}?width=${width}`
    } else {
        return rUrl
    }
}
```
Maybe this will help you😀

**Comment by dragonman225** [comment]
Thank you ! It works !
But instead of patching `notablog`, I add this URL conversion process to a lower level package [`nast-util-from-notionapi`](https://github.com/dragonman225/nast-util-from-notionapi), so it can also benefit people who are working with just data or developing other applications.

**Comment by aliforgetti** [comment]
> ```js
> const parseImageUrl = (url, width) => {
>     let rUrl
>     if (url.startsWith("https://s3")) {
>         let [parsedOriginUrl] = url.split("?")
>         rUrl = `${NOTION_BASE_URL}/image/${encodeURIComponent(parsedOriginUrl).replace("s3.us-west", "s3-us-west")}`
>     } else if (url.startsWith("/image")) {
>         rUrl = `${NOTION_BASE_URL}${url}`
>     } else {
>         rUrl = url
>     }
> 
>     if (width) {
>         return `${rUrl}?width=${width}`
>     } else {
>         return rUrl
>     }
> }
> ```
> 
> Maybe this will help you😀

Where do you paste this @mayneyao. Sorry a little new to this kind of thing :(

**Comment by aliforgetti** [comment]
> Thank you ! It works !
> But instead of patching `notablog`, I add this URL conversion process to a lower level package [`nast-util-from-notionapi`](https://github.com/dragonman225/nast-util-from-notionapi), so it can also benefit people who are working with just data or developing other applications.

@dragonman225 Can I please know where you add this and how did you fix this issue exactly?

**Comment by dragonman225** [comment]
https://github.com/dragonman225/nast/blob/6105e3fbc6ea7737380b060d5bf733772f0ef0cd/packages/nast-util-from-notionapi/src/util.ts#L63

**Comment by aliforgetti** [comment]
@dragonman225 I am confused as to how nast-util-from-notionapi integrates with the notablog-starter that you have provided.

**Comment by Demianeen** [comment]
@aliforgetti, have you managed to understand?
