### ISSUE TITLE
Add comment function code of utterances 

### ISSUE THREAD

**Issue by gendlee** [dragonman225/notablog#37]
Is it possible to automatically generate the code with the comment function of utterances at the end of the HTML file

**Comment by dragonman225** [comment]
The use of utterances to provide the comment function isn't default at the moment, but you can add it yourself. [Here's a brief guide](https://github.com/dragonman225/notablog/issues/32#issuecomment-1050733904). You just need to do it once and all posts generated later would have the comment function.
