### ISSUE TITLE
Allow different culture for date column

### ISSUE THREAD

**Issue by iFedaka** [dragonman225/notablog#39]
I can see that parseTable.ts has en-US culture hardcoded for date column.
https://github.com/dragonman225/notablog/blob/030981cdbeac9bc0b6aaf1dd24aac5ee4d6a596f/src/parseTable.ts

I'd like to be able to use different culture for date.
How to best achieve that?
The only idea I have is to add a new column with culture info, and in code a check if it's present then use it.

**Comment by dragonman225** [comment]
How about adding an option in the [config](https://github.com/dragonman225/notablog#folder-structure-of-notablog-starter) and let the code pick it up?
A concern of using a column is that I think "culture" is more of a per-site property than a per-page property, so having a "culture" column and letting users set it page by page seems too verbose.

My another idea is detecting it from the user's operating system, but I don't know how to do so, and there's a problem: if the user runs Notablog in a cloud service, it cannot detect what the user actually wants!

**Comment by iFedaka** [comment]
I agree that having a column is bad idea. It was the only idea I had.
I'll prepare a PR with optional option in the config.
