### ISSUE TITLE
Pure theme

### ISSUE THREAD

**Issue by sueszli** [dragonman225/notablog#44]
I noticed that the [pure theme](https://github.com/dragonman225/notablog-theme-pure) got removed that mimicked the default notion looks.

I would really appreciate if it could be added back.

**Comment by dragonman225** [comment]
Hi @sueszli, it's moved to be part of [notablog-starter](https://github.com/dragonman225/notablog-starter/tree/master/themes/pure-ejs) and the style is still Notion-like. Sorry for the confusion.

You can follow the [setup steps](https://github.com/dragonman225/notablog#getting-started) to see how it feels.

**Comment by sueszli** [comment]
Thanks!
