### ISSUE TITLE
Column Layout Broken and Gallery Incomlete

### ISSUE THREAD

**Issue by vwxyzjn** [dragonman225/notablog#5]
Hi, thanks for the amazing work. The generated site looks really amazing. I have two issues to report. 

1. The column layout seems to be broken. Please see the first screenshot as what is in https://dragonman225.js.org/block-test.html, and the second screenshot as what I generated today.

![image](https://user-images.githubusercontent.com/5555347/77771284-e1eca900-701c-11ea-9056-a5910016f233.png)
![image](https://user-images.githubusercontent.com/5555347/77771624-4b6cb780-701d-11ea-8b49-30f36944fad6.png)

![image](https://user-images.githubusercontent.com/5555347/77771318-eb761100-701c-11ea-8a5f-f6d5e5240ec1.png)

2. The gallery is missing things like tags and properties. 

What is actually there:
![image](https://user-images.githubusercontent.com/5555347/77771552-35f78d80-701d-11ea-8ef4-923e2e2405d7.png)

What is being rendered:
![image](https://user-images.githubusercontent.com/5555347/77771488-20826380-701d-11ea-90e7-c288af58aa5f.png)

Looking forward to hearing from you. Thanks for the great work again.

**Comment by dragonman225** [comment]
For the first issue:
I forgot to update [the theme's stylesheet](https://github.com/dragonman225/notablog-starter/commit/d6e1043d143b3e8b492fd46a2db2aa40b7cdc83a#diff-302f73cc73a8b5873c5044ec5de2e009) to match the HTML generated by the latest [rendering library](https://github.com/dragonman225/nast/tree/master/packages/nast-util-to-react), so the columns are broken. Now it's been updated, please use the latest [notablog-starter](https://github.com/dragonman225/notablog-starter) and the columns should be normal again.

**Comment by dragonman225** [comment]
For the second issue:
Yes, the gallery is missing many things, because it is not fully supported now. 😂
For details, refer to the [documentation](https://github.com/dragonman225/nast/tree/master/packages/nast-util-to-react#database-blocks) of the rendering library.

**Comment by vwxyzjn** [comment]
Thanks for the prompt reply. Indeed the column is being brought back. However, the display is still problematic. See

![image](https://user-images.githubusercontent.com/5555347/77783613-8aa40400-702f-11ea-99f1-078cbfab0cb0.png)

Feel free to test with my public page https://www.notion.so/043f2251b5db4aaba615a8d703455d8c?v=157e166961ff4f06acd38b02cc148fe1

**Comment by dragonman225** [comment]
For a quick fix, you may add

```css
.Video__Content > video {
  max-width: 100%;
}
```

in [this file](https://github.com/dragonman225/notablog-starter/blob/master/themes/pure/assets/css/theme.css).

But this time I will not update notablog-starter immediately, because this problem involves a bigger one, which is that in Notion, image, video, and embeds, all have the same logic for layout, so I've decided to come up with a general solution for this instead of patching separately.

**Comment by vwxyzjn** [comment]
I see. I can confirm that the CSS fixed the issue.

**Comment by vwxyzjn** [comment]
Thanks a lot for the fix

**Comment by vwxyzjn** [comment]
Regarding the second issue see dragonman225/nast#3

**Comment by kevchentw** [comment]
I noticed that dragonman225/nast#3 was merged. I wonder that when (or how) can we use it from notablog cli. Thank you.

**Comment by dragonman225** [comment]
I'll probably update Notablog in this weekend.

I'll need to publish a new version of `nast-util-to-react`, update that dependency's version number in Notablog's `package.json`, test it, and publish a new version of `notablog`.

It seems that most of tasks in the process rely on my actions, but if you want to try it earlier (and maybe see if there're bugs in your use case), in theory, you could

1. Clone the [`notablog`](https://github.com/dragonman225/notablog) repo, install (`npm install`) and build (`npm run build`) it.
2. Clone the [`nast`](https://github.com/dragonman225/nast) repo, follow the [instructions](https://github.com/dragonman225/nast#development) to set it up.
3. Edit the version number of `nast-util-to-react` in `notablog`'s [`package.json`](https://github.com/dragonman225/notablog/blob/3f04e5c081d80bd68d6c9f8d65e0ccca1bd9ffa2/package.json#L30), replace the version number with a local path (as described in [npm's documentation](https://docs.npmjs.com/files/package.json#local-paths)) to the [`nast-util-to-react`](https://github.com/dragonman225/nast/tree/master/packages/nast-util-to-react) package in the `nast` repo you've cloned.
4. Run [`notablog/bin/cli.js`](https://github.com/dragonman225/notablog/blob/master/bin/cli.js)

Disclaimer: I don't test these steps, instead, I just provide the concept on how to do on your own, but if you encounter any problem I will be glad to help.

**Comment by dragonman225** [comment]
v0.4.1 released, changes in [dragonman225/nast#3](https://github.com/dragonman225/nast/pull/3) are included.
Note that you also need to update your [notablog-starter](https://github.com/dragonman225/notablog-starter) to use it!
