### ISSUE TITLE
New images aren't properly linked

### ISSUE THREAD

**Issue by icarofr** [dragonman225/notablog#52]
All my old articles are translated to HTML pages just fine. However, when I upload a new picture, I only get a broken link, and the alt text is displayed.

All the old pictures started with a https://www.notion.so/signed/ URL and work quite well:
https://sold-out.io/phx/static/articles/555088-063.html

All the new ones point the \<img>s point straight to Amazon servers, and they're not displayed on page. New article for reference:
https://sold-out.io/phx/static/articles/FN6882-100.html

Really wished it could get a fix. We rely on notablog for our whole blogging infrastructure.

**Comment by dragonman225** [comment]
@icarofr Thanks for finding this bug! I haven't written a post for a while so I was not aware of it.

Just released a new version 0.8.1, update and let me know if it works.

**Comment by ghost** [comment]
Thank you so much, it's fixed!

Also honestly thanks for saving our whole blogging infrastructure, lol. We've been using Notion extensively as our CMS and it has only been possible thanks to your work. Thank you!

**Comment by dragonman225** [comment]
Glad to hear it works!
