### ISSUE TITLE
Support for Inline Math

### ISSUE THREAD

**Issue by vwxyzjn** [dragonman225/notablog#9]
The inline math is finally supported in notion https://www.notion.so/What-s-New-157765353f2c4705bd45474e5ba8b46c.

However, when rendering the with notablog, the inline math is not rendered properly

![image](https://user-images.githubusercontent.com/5555347/85031754-0c965b80-b14d-11ea-950c-84126802c320.png)

![image](https://user-images.githubusercontent.com/5555347/85031711-00120300-b14d-11ea-8808-dc4e31cd8c56.png)

**Comment by dragonman225** [comment]
Yeah, it is not yet supported.
Fortunately, Notablog is supporting the [math block](https://github.com/dragonman225/nast/blob/master/packages/nast-util-to-react/src/components/Equation.tsx), maybe we can take ideas from there, then find out how Notion encode the math string, and add the rendering logic to [this big switch-case](https://github.com/dragonman225/nast/blob/039fe7e49fca5a89bc36f3b4c73f57e62bc6f3c6/packages/nast-util-to-react/src/components/SemanticString.tsx#L65).

**Comment by yongzx** [comment]
@vwxyzjn @dragonman225 Create a hack to fix the issue: https://github.com/yongzx/notablog-fix-math-inline
Basically, I export the HTML file from Notion itself and transfer the relevant spans for inline-math blocks to the Notablog HTML file.

**Comment by dragonman225** [comment]
Cool! And thanks for reminding me of this issue, I looked into it again and found out [it wasn't](https://github.com/dragonman225/notionapi-agent/commit/d92e6b304b515190dd98550e906c281978b35232) [too hard](https://github.com/dragonman225/nast/commit/b9ac1cd6453522f8be3a79e3b16dc474062ea304) [to fix](https://github.com/dragonman225/nast/commit/365c1b84554ab41987e346fdcf6e20a5684cb0b0), I'll probably release a new version in a few days when I fix other bugs I found recently.

**Comment by dragonman225** [comment]
Inline math is supported in v0.5.0 or higher!
